// <auto-generated />
namespace SMApp.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addAttendancemodel1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAttendancemodel1));
        
        string IMigrationMetadata.Id
        {
            get { return "201612291805095_addAttendancemodel1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
